#### Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool

### Adv:
1) Works very well with structured Data

In [2]:
import pandas as pd
df = pd.read_csv('customers-100.csv')

In [3]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [ ]:
df = pd.read_csv('customers-100.csv', header = None)   # Assigns indexes to both rows and columns
df

,0,1,2,3,4,5,6,7,8,9,10,11
0,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
2,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
3,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
4,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
96,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
97,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
98,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
99,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
100,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [7]:
df = pd.read_csv('customers-100.csv', skiprows = 3)
df

,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
0,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
1,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
2,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
3,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
4,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
92,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
93,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
94,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
95,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
96,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [9]:
df = pd.read_csv('customers-100.csv', usecols = ['Index', 'Customer Id', 'First Name', 'Last Name',	'Company'])  # This will only display cols we have mentioned
df

,Index,Customer Id,First Name,Last Name,Company
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan"
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade"
...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal"
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross"

#### Data Structure  >> Series and DataFrame
### Series is 1D in nature
### Data Frame is made of various series and is 2D in nature

In [10]:
type(df)

pandas.core.frame.DataFrame

In [29]:
df = pd.read_csv('customers-100.csv')
df

,Index,Customer_Id,First_Name,Last_Name,Company,City,Country,Phone_1,Phone_2,Email,Subscription_Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [30]:
df.Country

0                          Chile
1                       Djibouti
2            Antigua and Barbuda
3             Dominican Republic
4     Slovakia (Slovak Republic)
                 ...
95                        Guyana
96                     Sri Lanka
97               Solomon Islands
98                         Aruba
99                      Honduras
Name: Country, Length: 100, dtype: object

In [ ]:
df['First_Name']   # This is used when there is no underscore between two words

0       Sheryl
1      Preston
2          Roy
3        Linda
4       Joanna
        ...
95        Karl
96        Lynn
97        Fred
98      Yvonne
99    Clarence
Name: First_Name, Length: 100, dtype: object

In [32]:
type(df['Customer_Id'])

pandas.core.series.Series

In [ ]:
type(df)  # DF is made from one or more series( There are several series here like index, Customer_Id, First_Name, etc)

pandas.core.frame.DataFrame

In [ ]:
l = [1,2,3]
s = pd.Series(l)  # Converts data into series
s

0    1
1    2
2    3
dtype: int64

In [37]:
type(s)

pandas.core.series.Series

In [38]:
s[2:4]

2    3
dtype: int64

In [39]:
s[1:]

1    2
2    3
dtype: int64

In [44]:
a = pd.Series([10,20,30,40,50], index = ["Aashish", "Karan", "Rishi", "Rahul", "Shobit"])
a

Aashish    10
Karan      20
Rishi      30
Rahul      40
Shobit     50
dtype: int64

In [45]:
a.index

Index(['Aashish', 'Karan', 'Rishi', 'Rahul', 'Shobit'], dtype='object')

In [49]:
a.reset_index()

     index   0
0  Aashish  10
1    Karan  20
2    Rishi  30
3    Rahul  40
4   Shobit  50

In [50]:
type(a)

pandas.core.series.Series

In [ ]:
a.reset_index(drop = True)   # It means throw the old index instead of keeping it as a column and create a new one

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [52]:
type(a)

pandas.core.series.Series

In [ ]:
pd.DataFrame(a)  # Converts

          0
Aashish  10
Karan    20
Rishi    30
Rahul    40
Shobit   50

In [ ]:
df.shape  # Give No of rows and columns

(100, 12)

In [54]:
df.columns

Index(['Index', 'Customer_Id', 'First_Name', 'Last_Name', 'Company', 'City',
       'Country', 'Phone_1', 'Phone_2', 'Email', 'Subscription_Date',
       'Website'],
      dtype='object')

In [ ]:
df.head(4)  # Gives 1st 4 rows

,Index,Customer_Id,First_Name,Last_Name,Company,City,Country,Phone_1,Phone_2,Email,Subscription_Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/

In [57]:
df.sample(3)   # Gives any 3 random row as sample

,Index,Customer_Id,First_Name,Last_Name,Company,City,Country,Phone_1,Phone_2,Email,Subscription_Date,Website
69,70,CC68FD1D3Bbbf22,Riley,Good,Wade PLC,Erikaville,Canada,6977745822,855-436-7641,alex06@galloway.com,2020-02-03,http://conway.org/
39,40,17aD8e2dB3df03D,Sherry,Garza,Anderson Ltd,West John,Poland,001-067-713-6440x158,(978)289-8785x5766,ann48@miller.com,2021-11-01,http://spence.com/
25,26,09D7D7C8Fe09aea,Marcus,Moody,Giles Ltd,Kaitlyntown,Panama,674-677-8623,909-277-5485x566,donnamullins@norris-barrett.org,2022-05-24,https://www.curry.com/

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer_Id        100 non-null    object
 2   First_Name         100 non-null    object
 3   Last_Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone_1            100 non-null    object
 8   Phone_2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription_Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [ ]:
list[df['First_Name']]  # Converts First_Name into a list

list[0       Sheryl
1      Preston
2          Roy
3        Linda
4       Joanna
        ...
95        Karl
96        Lynn
97        Fred
98      Yvonne
99    Clarence
Name: First_Name, Length: 100, dtype: object]

### Convert Series to DataFrame

In [62]:
b = pd.Series([1,2,3], index = [10, "Aashish", 4])
b

10         1
Aashish    2
4          3
dtype: int64

In [64]:
d = pd.DataFrame(b)
d

         0
10       1
Aashish  2
4        3

In [67]:
d['new column'] = 'Ram'
d

         0 new column
10       1        Ram
Aashish  2        Ram
4        3        Ram

In [68]:
d['new column']

10         Ram
Aashish    Ram
4          Ram
Name: new column, dtype: object

In [69]:
d

         0 new column
10       1        Ram
Aashish  2        Ram
4        3        Ram

In [ ]:
d.columns = ['id', "Name"]
d

         id Name
10        1  Ram
Aashish   2  Ram
4         3  Ram

In [72]:
d.reset_index(drop = True)

   id Name
0   1  Ram
1   2  Ram
2   3  Ram

In [74]:
df = pd.read_csv('customers-100.csv')
df

,Index,Customer_Id,First_Name,Last_Name,Company,City,Country,Phone_1,Phone_2,Email,Subscription_Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [ ]:
df_subset = df[['First_Name', 'Last_Name', 'Company', 'City', 'Country']]  # Creates a new dataframe from a Existing DataFrame
df_subset

,First_Name,Last_Name,Company,City,Country
0,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile
1,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti
2,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda
3,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic
4,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic)
...,...,...,...,...,...
95,Karl,Greer,Carey LLC,East Richard,Guyana
96,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka
97,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands
98,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba
99,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras

In [79]:
df1 = pd.read_excel('LUSID Excel.xlsx')
df1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Getting Started tutorials,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,Knowledge Base articles,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,or Contact us,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,LUSID accepts datetimes in any recognised Exce...,NaN,NaN,"LUSID also accepts UTC, UTS offsets and cutlabels",NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,Excel formats to show datetime,NaN,NaN,Additional formats,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,Enter the date to convert,2019-04-10 00:00:00,NaN,Standard UTC timestamp:,"""YYYY-MM-DDTHH:MM:SS.00Z""","Where Z indicates Zulu time (UTC+0), and is eq..."
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,This date has no time component,2019-04-10 00:00:00,NaN,Convert date into a string,2019-04-10T 13:30:45.55Z,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Specify time component,13:30:45.550000,NaN,UTC offset (not recognised as an excel date),2019-04-10T13:30:45+04:00,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,Add to your date and display the complete date...,2019-04-10 13:30:45.550000,NaN,Cutlabel,2019-04-10NSingaporeClose,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,Although the date can still appears without time,2019-04-10 13:30:45.550000,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,Add an hour to your datetime,2019-04-10 14:30:45.550000,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Subtract a minute from your datetime,2019-04-10 14:29:45.550000,NaN,NaN,NaN,NaN

In [87]:
df2 = pd.read_csv('https://raw.githubusercontent.com/tokern/piicatcher/master/tests/samples/sample-data.csv')
df2

,id,gender,birthdate,maiden_name,lname,fname,address,city,state,zip,phone,email,cc_type,cc_number,cc_cvc,cc_expiredate
0,172-32-1176,m,1958/04/21,Smith,White,Johnson,10932 Bigge Rd,Menlo Park,CA,94025,408 496-7223,jwhite@domain.com,m,5270 4267 6450 5516,123,2010/06/25
1,514-14-8905,f,1944/12/22,Amaker,Borden,Ashley,4469 Sherman Street,Goff,KS,66428,785-939-6046,aborden@domain.com,m,5370 4638 8881 3020,713,2011/02/01
2,213-46-8915,f,1958/04/21,Pinson,Green,Marjorie,309 63rd St. #411,Oakland,CA,94618,415 986-7020,mgreen@domain.com,v,4916 9766 5240 6147,258,2009/02/25
3,524-02-7657,m,1962/03/25,Hall,Munsch,Jerome,2183 Roy Alley,Centennial,CO,80112,303-901-6123,jmunsch@domain.com,m,5180 3807 3679 8221,612,2010/03/01
4,489-36-8350,m,1964/09/06,Porter,Aragon,Robert,3181 White Oak Drive,Kansas City,MO,66215,816-645-6936,raragon@domain.com,v,4929 3813 3266 4295,911,2011/12/01
5,514-30-2668,f,1986/05/27,Nicholson,Russell,Jacki,3097 Better Street,Kansas City,MO,66215,913-227-6106,jrussell@domain.com,a,345389698201044,232,2010/01/01
6,505-88-5714,f,1963/09/23,Mcclain,Venson,Lillian,539 Kyle Street,Wood River,NE,68883,308-583-8759,lvenson@domain.com,d,30204861594838,471,2011/12/01
7,690-05-5315,m,1969/10/02,Kings,Conley,Thomas,570 Nancy Street,Morrisville,NC,27560,919-656-6779,tconley@domain.com,v,4916 4811 5814 8111,731,2010/10/01
8,646-44-9061,M,1978/01/12,Kurtz,Jackson,Charles,1074 Small Street,New York,NY,10011,212-847-4915,cjackson@domain.com,m,5218 0144 2703 9266,892,2011/11/01
9,421-37-1396,f,1980/04/09,Linden,Davis,Susan,4222 Bedford Street,Jasper,AL,35501,205-221-9156,sdavis@domain.com,v,4916 4034 9269 8783,33,2011/04/01
10,461-97-5660,f,1975/01/04,Kingdon,Watson,Gail,3414 Gore Street,Houston,TX,77002,713-547-3414,gwatson@domain.com,v,4532 1753 6071 1112,694,2011/09/01
11,660-03-8360,f,1953/07/11,Onwunli,Garrison,Lisa,515 Hillside Drive,Lake Charles,LA,70629,337-965-2982,lgarrison@domain.com,v,4539 5385 7425 5825,680,2011/06/01
12,751-01-2327,f,1968/02/16,Simpson,Renfro,Julie,4032 Arron Smith Drive,Kaunakakai,HI,96748,808-560-1638,jrenfro@domain.com,m,5325 3256 9519 6624,238,2009/03/01
13,559-81-1301,m,1952/01/20,Mcafee,Heard,James,2865 Driftwood Road,San Jose,CA,95129,408-370-0031,jheard@domain.com,v,4532 4220 6922 9909,311,2010/09/01
14,624-84-9181,m,1980/01/16,Frazier,Reyes,Danny,3500 Diane Street,San Luis Obispo,CA,93401,805-369-0464,dreyes@domain.com,v,4532 0065 1968 5602,713,2009/11/01
15,449-48-3135,m,1982/06/14,Feusier,Hall,Mark,4986 Chapel Street,Houston,TX,77077,281-597-5517,mhall@domain.com,v,4556 0072 1294 7415,953,2010/05/01
16,477-36-0282,m,1961/03/10,Vasquez,Mceachern,Monte,456 Oral Lake Road,Minneapolis,MN,55401,952-412-3707,mmceachern@domain.com,m,5527 1247 5046 7780,889,2009/03/01
17,458-02-6124,m,1955/09/20,Pennebaker,Diaz,Christopher,582 Thrash Trail,Dallas,TX,75247,903-624-9156,cdiaz@domain.com,m,5299 1561 5689 1938,584,2011/08/01
18,044-34-6954,m,1967/05/28,Simpson,Lowe,Tim,1620 Maxwell Street,East Hartford,CT,6108,860-755-0293,tlowe@domain.com,m,5144 8691 2776 1108,616,2011/10/01
19,587-03-2682,f,1958/10/24,Dickerson,Oyola,Lynette,2489 O Conner Street,Pascagoula,MS,39567,228-938-2056,loyola@domain.com,v,4532 9929 3036 9308,991,2011/07/01
20,421-90-3440,f,1953/07/17,Kroeger,Morrison,Adriane,4696 Retreat Avenue,Birmingham,AL,35209,205-276-1807,amorrison@domain.com,v,4539 0031 3703 0728,322,2009/12/01
21,451-80-3526,m,1950/06/09,Parmer,Santos,Thomas,173 Lunetta Street,Fort Worth,TX,76104,940-859-1393,tsantos@domain.com,v,4716 6984 4983 6160,767,2011/09/01
22,300-62-3266,m,1965/02/10,Spain,Faulkner,Victor,1843 Olive Street,Toledo,OH,43602,419-340-3832,vfaulkner@domain.com,m,5548 0246 6336 5664,276,2010/02/01
23,322-84-2281,m,1977/08/19,Miley,Iorio,Albert,4899 University Hill Road,Springfield,IL,62701,217-615-6419,aiorio@domain.com,v,4916 6734 7572 5015,347,2010/02/01
24,465-73-5022,f,1964/06/20,Summers,Kaminski,Teresa,1517 Gambler Lane,Houston,TX,77006,281-906-2148,tkaminski@domain.com,m,5399 0706 4128 0178,721,2009/10/01
25,612-20-6832,m,1979/08/18,Banas,Edwards,Rick,4254 Walkers Ridge Way,Gardena,CA,90248,626-991-3620,redwards@domain.com,m,5293 8502 0071 3058,701,2010/08/01
26,687-05-8365,f,1976/05/24,Robbins,Peacock,Stacey,3396 Nancy Street,Raleigh,NC,27612,919-571-2339,speacock@domain.com,m,5495 8602 4508 6804,436,2011/02/01
27,205-52-0027,f,1950/03/26,Sanford,Nelson,Agnes,4213 High Meadow Lane,Avoca,PA,18641,570-480-8704,anelson@domain.com,m,5413 4428 0145 0036,496,2010/02/01
28,404-12-2154,f,1984/09/21,Garcia,Townsend,Mireille,2877 Glen Street,Paducah,KY,42003,270-408-7254,mtownsend@domain.com,v,4539 8219 0484 7598,710,2011/03/01
29,151-32-2558,f,1952/11/19,Stockdale,Zwick,Rebecca,784 Beechwood Avenue,Piscataway,NJ,8854,908-814-6733,rzwick@domain.com,v,5252 5971 4219 4116,173,2011/02/01

In [90]:
url_df = pd.read_html("https://catalog.data.gov/dataset/html-files")
url_df

[                     0                                                  1
 0                @type                                       dcat:Dataset
 1          accessLevel                                             public
 2   accrualPeriodicity                                          irregular
 3           bureauCode                                      [  "026:00" ]
 4         contactPoint  {  "fn": "CAROL WIESEMAN",  "@type": "vcard:Co...
 5          description  This is a resource where HTML files will be st...
 6         distribution  [  {  "@type": "dcat:Distribution",  "title": ...
 7           identifier                                       DASHLINK_332
 8               issued                                         2011-04-01
 9              keyword                  [  "ames",  "dashlink",  "nasa" ]
 10         landingPage        https://c3.nasa.gov/dashlink/resources/332/
 11            modified                                         2025-04-01
 12         programCode                                     [  "026:029" ]
 13           publisher  {  "name": "Dashlink",  "@type": "org:Organiza...
 14               title                                         HTML files]

In [ ]:
df3 = url_df[0]  # 0th index par dataframe hai
df3

                     0                                                  1
0                @type                                       dcat:Dataset
1          accessLevel                                             public
2   accrualPeriodicity                                          irregular
3           bureauCode                                      [  "026:00" ]
4         contactPoint  {  "fn": "CAROL WIESEMAN",  "@type": "vcard:Co...
5          description  This is a resource where HTML files will be st...
6         distribution  [  {  "@type": "dcat:Distribution",  "title": ...
7           identifier                                       DASHLINK_332
8               issued                                         2011-04-01
9              keyword                  [  "ames",  "dashlink",  "nasa" ]
10         landingPage        https://c3.nasa.gov/dashlink/resources/332/
11            modified                                         2025-04-01
12         programCode                                     [  "026:029" ]
13           publisher  {  "name": "Dashlink",  "@type": "org:Organiza...
14               title                                         HTML files

In [92]:
type(df3)

pandas.core.frame.DataFrame

In [95]:
df3.to_csv("Info.csv", index = False)
df3

                     0                                                  1
0                @type                                       dcat:Dataset
1          accessLevel                                             public
2   accrualPeriodicity                                          irregular
3           bureauCode                                      [  "026:00" ]
4         contactPoint  {  "fn": "CAROL WIESEMAN",  "@type": "vcard:Co...
5          description  This is a resource where HTML files will be st...
6         distribution  [  {  "@type": "dcat:Distribution",  "title": ...
7           identifier                                       DASHLINK_332
8               issued                                         2011-04-01
9              keyword                  [  "ames",  "dashlink",  "nasa" ]
10         landingPage        https://c3.nasa.gov/dashlink/resources/332/
11            modified                                         2025-04-01
12         programCode                                     [  "026:029" ]
13           publisher  {  "name": "Dashlink",  "@type": "org:Organiza...
14               title                                         HTML files

In [96]:
url = "https://raw.githubusercontent.com/sharmadhiraj/free-json-datasets/refs/heads/master/datasets/nobel-prize-winners-by-year.json"
pd.read_json(url)

     year                                            winners
0    1901  [{'category': 'chemistry', 'winners': [{'name'...
1    1902  [{'category': 'chemistry', 'winners': [{'name'...
2    1903  [{'category': 'chemistry', 'winners': [{'name'...
3    1904  [{'category': 'chemistry', 'winners': [{'name'...
4    1905  [{'category': 'chemistry', 'winners': [{'name'...
..    ...                                                ...
110  2015  [{'category': 'chemistry', 'winners': [{'name'...
111  2016  [{'category': 'chemistry', 'winners': [{'name'...
112  2017  [{'category': 'chemistry', 'winners': [{'name'...
113  2018  [{'category': 'chemistry', 'winners': [{'name'...
114  2019  [{'category': 'chemistry', 'winners': [{'name'...

[115 rows x 2 columns]

In [97]:
import requests
requests.get(url)