In [28]:
import pandas as pd

df = pd.read_csv('titanic dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
# Access rows and columns of dataframe >> 
# Implicit/integerinternal indexing  >> Indexing assigned by pands like [0,1,2.....]
# Explicit/Named Indexing >> Named Columns like here[Name, Sex, Age, Ticket,....]
df[0:100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,987,0,3,"Tenglin, Mr. Gunnar Isidor",male,25.0,0,0,350033,7.7958,NaN,S
96,988,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S
97,989,0,3,"Makinen, Mr. Kalle Edvard",male,29.0,0,0,STON/O 2. 3101268,7.9250,NaN,S
98,990,1,3,"Braf, Miss. Elin Ester Maria",female,20.0,0,0,347471,7.8542,NaN,S
99,991,0,3,"Nancarrow, Mr. William Henry",male,33.0,0,0,A./5. 3338,8.0500,NaN,S

In [ ]:
df.iloc[0:3] # Start from 0 and go till 2 (Integer Indexing)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [ ]:
df.loc[0:3]  # Start from 0 and go till 3 (Named Indexing)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S

In [ ]:
df.iloc[0:3, ['Name', 'Age']]  # This will throw an error so use loc in this case

IndexError: .iloc requires numeric indexers, got ['Name' 'Age']

In [7]:
df.loc[0:3, ['Name', 'Age']]

                               Name   Age
0                  Kelly, Mr. James  34.5
1  Wilkes, Mrs. James (Ellen Needs)  47.0
2         Myles, Mr. Thomas Francis  62.0
3                  Wirz, Mr. Albert  27.0

In [10]:
df.iloc[0:3, 0:4]

   PassengerId  Survived  Pclass                              Name
0          892         0       3                  Kelly, Mr. James
1          893         1       3  Wilkes, Mrs. James (Ellen Needs)
2          894         0       2         Myles, Mr. Thomas Francis

In [ ]:
# Series and DataFrames cannot be concatenated 
# If we keep the index same, then for series concatenation can happen

In [11]:
df.set_index('Name', inplace = True)

In [12]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Kelly, Mr. James",892,0,3,male,34.5,0,0,330911,7.8292,NaN,Q
"Wilkes, Mrs. James (Ellen Needs)",893,1,3,female,47.0,1,0,363272,7.0000,NaN,S
"Myles, Mr. Thomas Francis",894,0,2,male,62.0,0,0,240276,9.6875,NaN,Q
"Wirz, Mr. Albert",895,0,3,male,27.0,0,0,315154,8.6625,NaN,S
"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",896,1,3,female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Spector, Mr. Woolf",1305,0,3,male,NaN,0,0,A.5. 3236,8.0500,NaN,S
"Oliva y Ocana, Dona. Fermina",1306,1,1,female,39.0,0,0,PC 17758,108.9000,C105,C
"Saether, Mr. Simon Sivertsen",1307,0,3,male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
"Ware, Mr. Frederick",1308,0,3,male,NaN,0,0,359309,8.0500,NaN,S
"Peter, Master. Michael J",1309,0,3,male,NaN,1,1,2668,22.3583,NaN,C

In [13]:
df.reset_index()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Kelly, Mr. James",892,0,3,male,34.5,0,0,330911,7.8292,NaN,Q
1,"Wilkes, Mrs. James (Ellen Needs)",893,1,3,female,47.0,1,0,363272,7.0000,NaN,S
2,"Myles, Mr. Thomas Francis",894,0,2,male,62.0,0,0,240276,9.6875,NaN,Q
3,"Wirz, Mr. Albert",895,0,3,male,27.0,0,0,315154,8.6625,NaN,S
4,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",896,1,3,female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,"Spector, Mr. Woolf",1305,0,3,male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,"Oliva y Ocana, Dona. Fermina",1306,1,1,female,39.0,0,0,PC 17758,108.9000,C105,C
415,"Saether, Mr. Simon Sivertsen",1307,0,3,male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,"Ware, Mr. Frederick",1308,0,3,male,NaN,0,0,359309,8.0500,NaN,S
417,"Peter, Master. Michael J",1309,0,3,male,NaN,1,1,2668,22.3583,NaN,C

In [14]:
df.reset_index(drop = True)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,male,NaN,1,1,2668,22.3583,NaN,C

In [15]:
df.reset_index(inplace = True)

In [16]:
df

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Kelly, Mr. James",892,0,3,male,34.5,0,0,330911,7.8292,NaN,Q
1,"Wilkes, Mrs. James (Ellen Needs)",893,1,3,female,47.0,1,0,363272,7.0000,NaN,S
2,"Myles, Mr. Thomas Francis",894,0,2,male,62.0,0,0,240276,9.6875,NaN,Q
3,"Wirz, Mr. Albert",895,0,3,male,27.0,0,0,315154,8.6625,NaN,S
4,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",896,1,3,female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,"Spector, Mr. Woolf",1305,0,3,male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,"Oliva y Ocana, Dona. Fermina",1306,1,1,female,39.0,0,0,PC 17758,108.9000,C105,C
415,"Saether, Mr. Simon Sivertsen",1307,0,3,male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,"Ware, Mr. Frederick",1308,0,3,male,NaN,0,0,359309,8.0500,NaN,S
417,"Peter, Master. Michael J",1309,0,3,male,NaN,1,1,2668,22.3583,NaN,C

In [17]:
# Making dataframe from a dictionary

d = {'key1': [1,2,3,4],
     'key2': [5,6,7,8],
     'key3': [3,2,8,4]}
d

{'key1': [1, 2, 3, 4], 'key2': [5, 6, 7, 8], 'key3': [3, 2, 8, 4]}

In [18]:
pd.DataFrame(d)

   key1  key2  key3
0     1     5     3
1     2     6     2
2     3     7     8
3     4     8     4

In [2]:
import pandas as pd
df1 = pd.read_csv('taxonomy.csv')
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [3]:
df1.isnull()

     taxonomy_id   name  parent_id  parent_name
0          False  False       True         True
1          False  False      False        False
2          False  False      False        False
3          False  False      False        False
4          False  False      False        False
..           ...    ...        ...          ...
285        False  False      False        False
286        False  False      False        False
287        False  False      False        False
288        False  False      False        False
289        False  False      False        False

[290 rows x 4 columns]

In [ ]:
df1.isnull().sum()  # Tells us where the null values are

taxonomy_id     0
name            0
parent_id      11
parent_name    11
dtype: int64

In [5]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [ ]:
df1.dropna()  # This will drop all null values row wise  # Original df change nahi hua hai

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [8]:
df1.dropna(axis = 1)   # This will drop all null values Column wise

    taxonomy_id                          name
0           101                     Emergency
1        101-01             Disaster Response
2        101-02                Emergency Cash
3     101-02-01             Help Pay for Food
4     101-02-02       Help Pay for Healthcare
..          ...                           ...
285   111-01-07              Workplace Rights
286      111-02                     Mediation
287      111-03                        Notary
288      111-04                Representation
289      111-05  Translation & Interpretation

[290 rows x 2 columns]

In [ ]:
df1[['name']].dropna(axis = 1)  # Drop null values in column name

                             name
0                       Emergency
1               Disaster Response
2                  Emergency Cash
3               Help Pay for Food
4         Help Pay for Healthcare
..                            ...
285              Workplace Rights
286                     Mediation
287                        Notary
288                Representation
289  Translation & Interpretation

[290 rows x 1 columns]

### Imputation of missing values
#### Numeric data >> replace with mean and median  >> outlier treatment done >> then mean else median
#### Categorical data  >> replace with mode
#### Or impute missing values with some constants like 0

In [10]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [ ]:
df1.fillna("somevalue")   # Fills somevalue in place if null

    taxonomy_id                          name  parent_id           parent_name
0           101                     Emergency  somevalue             somevalue
1        101-01             Disaster Response        101             Emergency
2        101-02                Emergency Cash        101             Emergency
3     101-02-01             Help Pay for Food     101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare     101-02        Emergency Cash
..          ...                           ...        ...                   ...
285   111-01-07              Workplace Rights     111-01  Advocacy & Legal Aid
286      111-02                     Mediation        111                 Legal
287      111-03                        Notary        111                 Legal
288      111-04                Representation        111                 Legal
289      111-05  Translation & Interpretation        111                 Legal

[290 rows x 4 columns]

In [12]:
df1.fillna(0)   # Fills 0 in place if null

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency         0                     0
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [13]:
df1.fillna(df1.mean())   # Fills somevalue in place if null

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [15]:
data1 = {
    'A' : [1,2,3,None,4,None,5,6,None,7,8],
    'B' : [1,None,None,2,3,4,5,None,6,7,None]
}

df2 = pd.DataFrame(data1)
df2

      A    B
0   1.0  1.0
1   2.0  NaN
2   3.0  NaN
3   NaN  2.0
4   4.0  3.0
5   NaN  4.0
6   5.0  5.0
7   6.0  NaN
8   NaN  6.0
9   7.0  7.0
10  8.0  NaN

In [ ]:
df2.A.fillna(df2['A'].mean())  # Impute null values with mean

0     1.0
1     2.0
2     3.0
3     4.5
4     4.0
5     4.5
6     5.0
7     6.0
8     4.5
9     7.0
10    8.0
Name: A, dtype: float64

In [ ]:
df2.A.fillna(df2['A'].median())  # Impute null values with median

0     1.0
1     2.0
2     3.0
3     4.5
4     4.0
5     4.5
6     5.0
7     6.0
8     4.5
9     7.0
10    8.0
Name: A, dtype: float64

In [20]:
df2

      A    B
0   1.0  1.0
1   2.0  NaN
2   3.0  NaN
3   NaN  2.0
4   4.0  3.0
5   NaN  4.0
6   5.0  5.0
7   6.0  NaN
8   NaN  6.0
9   7.0  7.0
10  8.0  NaN

In [ ]:
# df2.fillna(method = 'ffill')   # This is forward fill pehle wali(non-null) value ko null ki jagah impute kardo
df2.ffill()  # New syntax

C:\Users\Aashish Singh\AppData\Local\Temp\ipykernel_18164\3106498531.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method = 'ffill')

      A    B
0   1.0  1.0
1   2.0  1.0
2   3.0  1.0
3   3.0  2.0
4   4.0  3.0
5   4.0  4.0
6   5.0  5.0
7   6.0  5.0
8   6.0  6.0
9   7.0  7.0
10  8.0  7.0

In [23]:
df2

      A    B
0   1.0  1.0
1   2.0  NaN
2   3.0  NaN
3   NaN  2.0
4   4.0  3.0
5   NaN  4.0
6   5.0  5.0
7   6.0  NaN
8   NaN  6.0
9   7.0  7.0
10  8.0  NaN

In [ ]:
df2.fillna(method = 'bfill')   # This is backward fill baad wali(non-null) value ko null ki jagah impute kardo
df2.bfill()  # New Syntax

C:\Users\Aashish Singh\AppData\Local\Temp\ipykernel_18164\2686620435.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method = 'bfill')   # This is backward fill pehle wali value ko null ki jagah impute kardo

      A    B
0   1.0  1.0
1   2.0  2.0
2   3.0  2.0
3   4.0  2.0
4   4.0  3.0
5   5.0  4.0
6   5.0  5.0
7   6.0  6.0
8   7.0  6.0
9   7.0  7.0
10  8.0  NaN

In [ ]:
df2.duplicated().sum()  # Gives duplicate values

np.int64(0)

In [29]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [33]:
df = pd.read_csv('titanic dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [35]:
df.mean(numeric_only = True)

PassengerId    1100.500000
Survived          0.363636
Pclass            2.265550
Age              30.272590
SibSp             0.447368
Parch             0.392344
Fare             35.627188
dtype: float64

In [37]:
df.median(numeric_only = True)

PassengerId    1100.5000
Survived          0.0000
Pclass            3.0000
Age              27.0000
SibSp             0.0000
Parch             0.0000
Fare             14.4542
dtype: float64

In [38]:
df.std(numeric_only = True)

PassengerId    120.810458
Survived         0.481622
Pclass           0.841838
Age             14.181209
SibSp            0.896760
Parch            0.981429
Fare            55.907576
dtype: float64

In [ ]:
# What is the average fare paid by people who survived?

In [ ]:
df[df.Survived == 1]['Fare'].mean()  # Average Fare paid by people who survived

np.float64(49.747698684210526)

In [41]:
df[df.Survived == 0]['Fare'].mean()  # Average Fare paid by people who didn't survive

np.float64(27.527876981132078)

In [ ]:
# groupby

df.groupby('Survived').mean(numeric_only = True)  # Gives average of all attibutes in survived class

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0         1102.620301  2.334586  30.272732  0.379699  0.274436  27.527877
1         1096.789474  2.144737  30.272362  0.565789  0.598684  49.747699

In [ ]:
import numpy as np
df.groupby('Survived')['Fare'].agg(['min','max','mean','median','count','std','var'])

           min       max       mean   median  count        std          var
Survived
0         0.00  262.3750  27.527877  13.0000    265  41.079423  1687.518983
1         6.95  512.3292  49.747699  21.5125    152  73.108716  5344.884359

In [49]:
df.groupby(['Sex','Pclass'])['Survived'].sum()

Sex     Pclass
female  1         50
        2         30
        3         72
male    1          0
        2          0
        3          0
Name: Survived, dtype: int64

In [50]:
df.groupby(['Sex','Pclass'])['Survived'].sum().to_frame()

               Survived
Sex    Pclass
female 1             50
       2             30
       3             72
male   1              0
       2              0
       3              0

In [51]:
df.groupby(['Sex','Pclass'])['Survived'].sum().unstack()

Pclass   1   2   3
Sex
female  50  30  72
male     0   0   0

In [ ]:
a = df.groupby('Pclass').sum(numeric_only = True)  # Sum of values of all Values by Pclass class
a

        PassengerId  Survived      Age  SibSp  Parch        Fare
Pclass
1            117510        50  4010.00     51     41  10087.9918
2            103968        30  2532.42     35     32   2064.7957
3            238531        72  3508.08    101     91   2703.7501

In [ ]:
a.T   # Transpose

Pclass                 1            2            3
PassengerId  117510.0000  103968.0000  238531.0000
Survived         50.0000      30.0000      72.0000
Age            4010.0000    2532.4200    3508.0800
SibSp            51.0000      35.0000     101.0000
Parch            41.0000      32.0000      91.0000
Fare          10087.9918    2064.7957    2703.7501