In [2]:
import pandas as pd
df = pd.read_csv('titanic dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [6]:
df1 = df[['Name', 'Sex', 'Age']][0:5]
df1

                                           Name     Sex   Age
0                              Kelly, Mr. James    male  34.5
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0
2                     Myles, Mr. Thomas Francis    male  62.0
3                              Wirz, Mr. Albert    male  27.0
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0

In [7]:
df2 = df[['Name', 'Sex', 'Age']][5:10]
df2

                                        Name     Sex   Age
5                 Svensson, Mr. Johan Cervin    male  14.0
6                       Connolly, Miss. Kate  female  30.0
7               Caldwell, Mr. Albert Francis    male  26.0
8  Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0
9                    Davies, Mr. John Samuel    male  21.0

In [13]:
pd.concat([df1,df2], axis = 0)   # Concatenate padas objects along a particular axis.

                                           Name     Sex   Age
0                              Kelly, Mr. James    male  34.5
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0
2                     Myles, Mr. Thomas Francis    male  62.0
3                              Wirz, Mr. Albert    male  27.0
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0
5                    Svensson, Mr. Johan Cervin    male  14.0
6                          Connolly, Miss. Kate  female  30.0
7                  Caldwell, Mr. Albert Francis    male  26.0
8     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0
9                       Davies, Mr. John Samuel    male  21.0

### Merge
Merging on the basis of common elements

In [19]:
df1 = pd.DataFrame({'key1': [1,2,4,5,6],
                    'key2': [4,5,6,7,8],
                    'key3': [3,4,5,6,6]
                   })

df1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [20]:
df2 = pd.DataFrame({'key1': [1,2,45,6,65],
                    'key4': [56,5,6,7,8],
                    'key5': [3,56,5,6,6]
                   })

df2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    65     8     6

In [ ]:
pd.merge(df1,df2, how = 'inner')  # Key1 ke common values jis row mein hai un rows ke elements ko new tale mein add kardo

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     6     8     6     7     6

In [ ]:
pd.merge(df1,df2, how = 'left')  # Left join >> Left ke saare elements and key1 ke common elements jis row mein hai df2 ke andar joh aayenge

   key1  key2  key3  key4  key5
0     1     4     3  56.0   3.0
1     2     5     4   5.0  56.0
2     4     6     5   NaN   NaN
3     5     7     6   NaN   NaN
4     6     8     6   7.0   6.0

In [ ]:
pd.merge(df1,df2, how = 'right')   # Right join >> Right ke saare elements and key1 ke common elements jis row mein hai df1 ke andar joh aayenge

   key1  key2  key3  key4  key5
0     1   4.0   3.0    56     3
1     2   5.0   4.0     5    56
2    45   NaN   NaN     6     5
3     6   8.0   6.0     7     6
4    65   NaN   NaN     8     6

In [ ]:
pd.merge(df1,df2, how = 'cross')   # 1st row of df1 with all rows of df2, then 2nd row of df1 with all rows of df2 and so on

    key1_x  key2  key3  key1_y  key4  key5
0        1     4     3       1    56     3
1        1     4     3       2     5    56
2        1     4     3      45     6     5
3        1     4     3       6     7     6
4        1     4     3      65     8     6
5        2     5     4       1    56     3
6        2     5     4       2     5    56
7        2     5     4      45     6     5
8        2     5     4       6     7     6
9        2     5     4      65     8     6
10       4     6     5       1    56     3
11       4     6     5       2     5    56
12       4     6     5      45     6     5
13       4     6     5       6     7     6
14       4     6     5      65     8     6
15       5     7     6       1    56     3
16       5     7     6       2     5    56
17       5     7     6      45     6     5
18       5     7     6       6     7     6
19       5     7     6      65     8     6
20       6     8     6       1    56     3
21       6     8     6       2     5    56
22       6     8     6      45     6     5
23       6     8     6       6     7     6
24       6     8     6      65     8     6

In [27]:
df1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [28]:
df2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    65     8     6

In [ ]:
pd.merge(df1,df2, how = 'outer')  # Will give all keys from both dataframes (key1/common column ke saare values aajayenge)

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   NaN   NaN
4     6   8.0   6.0   7.0   6.0
5    45   NaN   NaN   6.0   5.0
6    65   NaN   NaN   8.0   6.0

In [ ]:
pd.merge(df1,df2, how = 'left', left_on = 'key2', right_on = 'key4')  # Custom comman key

   key1_x  key2  key3  key1_y  key4  key5
0       1     4     3     NaN   NaN   NaN
1       2     5     4     2.0   5.0  56.0
2       4     6     5    45.0   6.0   5.0
3       5     7     6     6.0   7.0   6.0
4       6     8     6    65.0   8.0   6.0

### Join 
Merging on the basis of indexes

In [30]:
df1 = pd.DataFrame({'key1': [1,2,4,5,6],
                    'key2': [4,5,6,7,8],
                    'key3': [3,4,5,6,6]
                   },
index = ['a','b','c','d','e']
)

df1

   key1  key2  key3
a     1     4     3
b     2     5     4
c     4     6     5
d     5     7     6
e     6     8     6

In [33]:
df2 = pd.DataFrame({'key4': [1,2,45,6,65],
                    'key5': [56,5,6,7,8],
                    'key6': [3,56,5,6,6]
                   },
index = ['a','b','h','i','j']
)

df2

   key4  key5  key6
a     1    56     3
b     2     5    56
h    45     6     5
i     6     7     6
j    65     8     6

In [34]:
df1.join(df2, how = 'inner')  # Join at common index of df1 and df2

   key1  key2  key3  key4  key5  key6
a     1     4     3     1    56     3
b     2     5     4     2     5    56

In [35]:
df1.join(df2, how = 'left')

   key1  key2  key3  key4  key5  key6
a     1     4     3   1.0  56.0   3.0
b     2     5     4   2.0   5.0  56.0
c     4     6     5   NaN   NaN   NaN
d     5     7     6   NaN   NaN   NaN
e     6     8     6   NaN   NaN   NaN

In [36]:
df1.join(df2, how = 'right')

   key1  key2  key3  key4  key5  key6
a   1.0   4.0   3.0     1    56     3
b   2.0   5.0   4.0     2     5    56
h   NaN   NaN   NaN    45     6     5
i   NaN   NaN   NaN     6     7     6
j   NaN   NaN   NaN    65     8     6

In [38]:
df1.join(df2, how = 'outer')

   key1  key2  key3  key4  key5  key6
a   1.0   4.0   3.0   1.0  56.0   3.0
b   2.0   5.0   4.0   2.0   5.0  56.0
c   4.0   6.0   5.0   NaN   NaN   NaN
d   5.0   7.0   6.0   NaN   NaN   NaN
e   6.0   8.0   6.0   NaN   NaN   NaN
h   NaN   NaN   NaN  45.0   6.0   5.0
i   NaN   NaN   NaN   6.0   7.0   6.0
j   NaN   NaN   NaN  65.0   8.0   6.0

In [39]:
df1.join(df2, how = 'cross')

    key1  key2  key3  key4  key5  key6
0      1     4     3     1    56     3
1      1     4     3     2     5    56
2      1     4     3    45     6     5
3      1     4     3     6     7     6
4      1     4     3    65     8     6
5      2     5     4     1    56     3
6      2     5     4     2     5    56
7      2     5     4    45     6     5
8      2     5     4     6     7     6
9      2     5     4    65     8     6
10     4     6     5     1    56     3
11     4     6     5     2     5    56
12     4     6     5    45     6     5
13     4     6     5     6     7     6
14     4     6     5    65     8     6
15     5     7     6     1    56     3
16     5     7     6     2     5    56
17     5     7     6    45     6     5
18     5     7     6     6     7     6
19     5     7     6    65     8     6
20     6     8     6     1    56     3
21     6     8     6     2     5    56
22     6     8     6    45     6     5
23     6     8     6     6     7     6
24     6     8     6    65     8     6

In [40]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [42]:
df.Fare

0        7.8292
1        7.0000
2        9.6875
3        8.6625
4       12.2875
         ...
413      8.0500
414    108.9000
415      7.2500
416      8.0500
417     22.3583
Name: Fare, Length: 418, dtype: float64

In [ ]:
# Convert fare from euros to inr
df['Fare_INR'] = df['Fare'].apply(lambda x: x*110)   # Converts Fare in INR from Euros
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,861.212
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,770.000
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,1065.625
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,952.875
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,1351.625
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,885.500
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,11979.000
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,797.500
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,885.500
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,2459.413

In [45]:
df['Name']

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [50]:
df['Name_len'] = df['Name'].apply(len)   # Gives us length of each name in each row
df['Name_len']

0      16
1      32
2      25
3      16
4      44
       ..
413    18
414    28
415    28
416    19
417    24
Name: Name_len, Length: 418, dtype: int64

In [51]:
def convert(x):
    return x*110

In [52]:
df['Fare'].apply(convert)

0        861.212
1        770.000
2       1065.625
3        952.875
4       1351.625
         ...
413      885.500
414    11979.000
415      797.500
416      885.500
417     2459.413
Name: Fare, Length: 418, dtype: float64

In [64]:
data = {"a": [1,2,3,4],
        "b": [5,5,6,7],
        "c": ["aa","sh","is","h"]}
df1 = pd.DataFrame(data)

df1

   a  b   c
0  1  5  aa
1  2  5  sh
2  3  6  is
3  4  7   h

In [65]:
df1.set_index('c', inplace = True)  # Here we are setting column c as an index
df1

    a  b
c
aa  1  5
sh  2  5
is  3  6
h   4  7

In [62]:
df1.reset_index(inplace = True)
df1

    c  a  b
0  aa  1  5
1  sh  2  5
2  is  3  6
3   h  4  7

In [66]:
df1.reset_index(drop = True, inplace = True)
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [ ]:
df1.reindex([2,0,1,3])  # Rearranges the index of the dataframe

   a  b
2  3  6
0  1  5
1  2  5
3  4  7

In [72]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [ ]:
for i in df1.iterrows():   # Iterrate row wise
    print(i, "-----")

(0, a    1
b    5
Name: 0, dtype: int64) -----
(1, a    2
b    5
Name: 1, dtype: int64) -----
(2, a    3
b    6
Name: 2, dtype: int64) -----
(3, a    4
b    7
Name: 3, dtype: int64) -----

In [71]:
for i in df1.items():  # Column wise Itteration
    print(i)

('a', 0    1
1    2
2    3
3    4
Name: a, dtype: int64)
('b', 0    5
1    5
2    6
3    7
Name: b, dtype: int64)

In [75]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [73]:
def func_sum(x):
    return x.sum()

In [ ]:
df1.apply(func_sum, axis = 0)  # Gives sum of a and b column wise using external function

a    10
b    23
dtype: int64

In [ ]:
df1.apply(func_sum, axis = 1)   # Gives sum of a and b row wise using external function

0     6
1     7
2     9
3    11
dtype: int64

In [77]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [ ]:
df1.map(lambda x: x**2,)  # map is used if we want to apply function on whole dataframe and not only single series

    a   b
0   1  25
1   4  25
2   9  36
3  16  49

In [80]:
df1.sort_values(by = 'a')

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [ ]:
df.sort_values(by = 'Fare')  # Sort Values by Fare in ascending

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,Name_len
343,1235,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,56356.212,63
69,961,1,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.0,1,4,19950,263.0000,C23 C25 C27,S,28930.000,35
53,945,1,1,"Fortune, Miss. Ethel Flora",female,28.0,3,2,19950,263.0000,C23 C25 C27,S,28930.000,26
59,951,1,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C,28861.250,27
64,956,0,1,"Ryerson, Master. John Borie",male,13.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,28861.250,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,1025,0,3,"Thomas, Mr. Charles P",male,NaN,1,0,2621,6.4375,NaN,C,708.125,21
21,913,0,3,"Olsen, Master. Artur Karl",male,9.0,0,1,C 17368,3.1708,NaN,S,348.788,25
266,1158,0,1,"Chisholm, Mr. Roderick Robert Crispin",male,NaN,0,0,112051,0.0000,NaN,S,0.000,37
372,1264,0,1,"Ismay, Mr. Joseph Bruce",male,49.0,0,0,112058,0.0000,B52 B54 B56,S,0.000,23
152,1044,0,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S,NaN,18